### ISSUE TITLE
Install CI (Continuous Integration)

### ISSUE THREAD

**Issue by souljungkim** [suy427/mamas-estate#24]
## 현상황
`CI` (Continuous Integration) 의 부재

## 문제점
미리 자동화 인프라를 설치하고 익숙해지면 계속 능숙하게 사용할 것이다.
그렇지 않고 계속 미루면, 그것에 익숙해질 것이다.
더욱이 이를 통해 **자동으로** `테스트` 및 `배포`를 함으로써 `시간 및 노동비용을 절약`할 수 있다.
하지만! 사용하지 않는다면 그만큼의 시간비용을 부담해야한다는 것이 문제이다.

### 1. CI 도입
- `Test`: Local에서는 물론 특정지점(특정Branch Merge / Tagging / Pull Request 등..)에서 작용하게 하여 잘못된 소스코드가 Master로 들어가지않게 미연에 방지한다. (`품질향상`)
- `Deploy`: 자동으로 Release영역에 파일을 배포할 수 있다. (`시간-노동 비용절약`)

### 2. Travis-CI
- Github와 연동가능한 가장 유명한 도구를 사용하자. 간단하다.
- ⭕️ https://travis-ci.org/ 을 이용한다. 
- ❌ https://travis-ci.com/ 는 유료버전이므로 자칫 실수로 오인해서 작업에 차질을 겪지 않도록 한다.

**Comment by suy427** [comment]
i totally agree with this opinion and #23 
but as i said at #23 i have no confidence whether i could complete these things all.
because i have to learn these things before apply these things...

in my opinion, the first thing that i have to do is to finish the work that i'm doing now.
i'm making a basic page template with HTML&js and it will be done soon.
(i have to do one thing at one time.. i can't do things at once..TT)

and then, i will make test code. CI & coverage tools are the next.
i wanna ask your opinion about it.

(thank you soooooo much for your help :D)

**Comment by suy427** [comment]
maybe i will finish the basic ui-template until this weekend :)

**Comment by souljungkim** [comment]
@suy427 
Installation is very easy.
I can organize the documents and show them. 

You don't have to focus too much on other tools.
"`Many a little makes a mickle.`" (https://m.blog.naver.com/PostView.nhn?blogId=jsj5564&logNo=220495302637&proxyReferer=https%3A%2F%2Fwww.google.com%2F) 😆

**Comment by souljungkim** [comment]
@suy427  beautiful ! ee6ce6a 002f680
but you work too hard. take some rest.

**Comment by suy427** [comment]
thank you! but i'm using H2 DB(in-memory db that provides JPA) instead of mysql for now
due to travis mysql connection fail...
i have to fix it someday :D
